export const FIND_SEARCHED_CITIES_FROM = 'FIND_SEARCHED_CITIES_FROM';
export const FIND_SEARCHED_CITIES_TO = 'FIND_SEARCHED_CITIES_TO';
export const CLOSE_SEARCHED_CITIES_BOX = 'CLOSE_SEARCHED_CITIES_BOX';
export const SET_DESTINATION_FROM = 'SET_DESTINATION_FROM';
export const SET_DESTINATION_TO = 'SET_DESTINATION_TO';